Training:
  train_test_split_size: 0.8
  accelerator: "gpu"
  seed: 42
  epochs: 40
  n_fold: 5
  batch_size: 64
  early_stopping: 5
  wokers: 0
  model_save_path: ./save_models/
  data_config:
    input_data_name: "Bleached Softwood Kraft Pulp Futures Historical Data.csv"
    target: "Price"
    drop_cols:
      - Open
      - High
      - Low
      - Vol.
      - Change %
    features:
    use_standardization: False

  model_lstm:
    lr: 1e-2
    hidden_size: 32 # Size of the LSTM hidden state
    num_layers: 1 # Number of LSTM layers (stacked)
    dropout: 0.2 # Dropout between LSTM layers (if num_layers > 1)
    weight_decay: 1e-3

  scheduler:
    type: "ReduceLROnPlateau"
    factor: 0.5
    patience: 10
    min_lr: 1e-5

Prediction:
  timewindow: 7 # in days
